pull_request_rules:
  - name: Automatically merge successful scala-steward PRs (2.12.12/2.13.4)
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.4, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.12, adopt@1.8)
    actions:
      merge:
        method: merge
        strict: true
  - name: Automatically merge successful scala-steward PRs (2.12.12/2.13.5)
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.5, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.12, adopt@1.8)
    actions:
      merge:
        method: merge
        strict: true
  - name: Automatically merge successful scala-steward PRs (2.12.13/2.13.4)
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.4, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.13, adopt@1.8)
    actions:
      merge:
        method: merge
        strict: true
  - name: Automatically merge successful scala-steward PRs (2.12.13/2.13.5)
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.5, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.13, adopt@1.8)
    actions:
      merge:
        method: merge
        strict: true
