sudo: false

language: scala

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

env:
  - SCALAJS_VERSION=0.6.33
  - SCALAJS_VERSION=1.1.1

jobs:
  include:
    - script: "sbt +test"
    - stage: publish
      name: Publish
      if: tag IS present
      script: "sbt +publish"
