language: scala

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

env:
  - SCALAJS_VERSION=0.6.33
  - SCALAJS_VERSION=1.1.1

script: "sbt +test"

deploy:
  provider: script
  script: sbt +publish
  on:
    tags: true
